version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginxv1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/index.html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
